import './globals.scss'
import { Inter } from 'next/font/google'
import Header from '@/layouts/components/Header'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'IC đây rồi',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header />
        {children}
      </body>
    </html>
  )
}
